# Generated by Django 5.2.7 on 2026-06-16 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaMuseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo_guia', models.CharField(max_length=60)),
                ('anios_experiencia_guia', models.IntegerField()),
                ('idiomas_hablados', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Museo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('ciudad', models.CharField(max_length=45)),
                ('anio_fundacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exibicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_exhibicion', models.CharField(max_length=50)),
                ('meses_duracion', models.IntegerField()),
                ('costo_produccion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tematica', models.CharField(max_length=50)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guiaexh', to='institucion.guiamuseo')),
            ],
        ),
        migrations.AddField(
            model_name='guiamuseo',
            name='museo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='museomain', to='institucion.museo'),
        ),
    ]
